<?php

namespace AppBundle\Repository;

/**
 * Carro
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Carro extends \Doctrine\ORM\EntityRepository
{
}
