<?php

namespace AppBundle\Repository;

/**
 * Categoria
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categoria extends \Doctrine\ORM\EntityRepository
{
}
