<?php

namespace AppBundle\Repository;

/**
 * Montadora
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Montadora extends \Doctrine\ORM\EntityRepository
{
}
