<?php

namespace AppBundle\Repository;

/**
 * Pedido
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pedido extends \Doctrine\ORM\EntityRepository
{
}
