<?php

namespace AppBundle\Repository;


use AbstractBundle\Resources\traits\GenerateProperties;
use Symfony\Component\HttpKernel\Exception\HttpException;
use AppBundle\Entity\User;
use Symfony\Component\HttpFoundation\ParameterBag;
use AbstractBundle\Repository\AbstractRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractRepository
{

    /**
     * @param $params ParameterBag
     * @param User $user
     * @return HttpException | User
     */
    public function persist($params, User $user)
    {
        try {
            return
                $this->generateProperties($params, $user);
        } catch (\Exception $e) {
            throw new HttpException(500, $e->getMessage());
        }
    }
}
