<?php

namespace AppBundle\Repository;

/**
 * UsuarioInfo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioInfo extends \Doctrine\ORM\EntityRepository
{
}
